language: node_js
node_js: '10'

branches:
  only:
  - master

jobs:
  include:
  - stage: deploy
    addons:
      chrome: stable
    before_install:
    - npm install -g @angular/cli
    - google-chrome-stable --headless --disable-gpu
    install: npm install
    deploy:
      provider: heroku
      api_key:
        secure: "b7ce0507-600b-4da2-b6b1-5f51ecb0d5a2"
      app: itea-ci
      on:
        branch: master
        tags: false
  - stage: after deploy test
    script: 'curl https://itea-ci.herokuapp.com'
