language: node_js
node_js: '10'
addons:
  firefox: latest
before_install: npm install -g @angular/cli
install: npm install
branches:
  only:
  - "/.*/"
jobs:
  include:
  - stage: build
    deploy:
      provider: heroku
      api_key:
        secure: qSsJFiVBHGIvjEhn1MB5HuHD943Ei4tCuJNLG8qrQ+4R/8/uOhshF407cfujxN0yJ3F+6q0/DSPM/XF2TODXvs2MySoSX/LmTpA9zFqNH8LnzfRSDk7NjWG9OV4axU3+Pn1irDODbdwn/8jH86n6QxVzhvIetauL3N6Qb8VSUdrsXj3Da3+obrB9fJDGQjwcq5LamVEVa1ZuDDcp2tiOwbhWv5Z+UU1O0blb2nnw20+OCSxEKYHGFpLCoGxr5AtQ9PRaFCoh+2WmB4+nR8uLFsQiAZfRKXvy4pWp0waLAkoHTUn3oiRexpnMRGNNzWyCn7pPd8ofVeReqUTEeriu83QrprwU4p4VgRuDsMpaI/mrhJmeE3k1H0kkjgaI/szp9GJPs/B/k+00hKAvZJmGGTkULG1G3jxQtgsS2u38LFeXkw6dWlPck/pmzkDWncGTA6d1FVl2O4Dr8YdvNDv3rKNHxmMf1T5PTxW3kv1ry2QKQ8AUWX0peCLJR7MQZeLUEKNRrwzQ1YDfKl6okczep3P0Wa/j8M0VNGz0wbWAP999UElbJPtBHFPKOrPR6KkYYiMHdce/xjSrG4w/Ay1NUPLyy89a6DoWN9PkAzw/gAVVxNqs+KLPY4JTeavhmzz454qYPzxA9aKLZ+kUvP1h+SKeleaL1peXAgw+0jkVD/Y=
      app: itea-ci
      on:
        branch: master
        tags: true
    after_deploy: curl https://itea-ci.herokuapp.com
env:
  global:
  - MOZ_HEADLESS=1
