language: node_js
node_js: '10'
addons:
  firefox: latest
before_install: npm install -g @angular/cli
install: npm install
branches:
  only:
  - "/.*/"
jobs:
  include:
  - stage: build
    deploy:
      provider: heroku
      api_key:
        secure: FUtAWJKzoxD+N7f0XpB0uxmjQvrOHp/rryS/tPrHQXoijGCd/pL6Hh5LA/IO5ZAR7WA0HPKVg6HG5IDVjV+QQLnzca7E0yV61l2x+Z+YmRlxFUp84W58wdStZkgFE+td7MoVGwCJGn5KfUD7TcUBXDHGu6S+IsSCygJjVUiFEnDHR6f/Kz2yNADizC3ty103N1JCJ81lN326DAbsIdFIXS35iUsgoPfWpDsCbEhlEn7yWORK1Dx6/uZaTnqLkL7UFkszwhpxK2c1kiZDbG+B9WkDyHdoQc0s7ekpIQ94q1qzkCYyqXkSJw6CFAAD3ZAVQEx+78Io541FWpct/0IO6AYf2WZujJJln019p7xFgwLwBKAoHq8h03kk0KF6W62v+zLfe0/Mwo5vSfrDZl39631mBwWjPi7c7raSavATXHDhDh/cxEOFddUzpGqaZiGrU9NgpP+n6FB6675fF/KaWu0i1OYmky1HijfrMJI2YSvV13S7Z7n53s3Jmo2+R6DWXeuwN4UGW6Kd2x+cmqTW2FvS1rfTdENyhMuKc5wOjA/UJuoKl6dPt6MtREwRnPu69kl1NI1YoWD7wWNMqLn4RBdrKD+k6PzvrLR1t8lg3jY1EuQtCkyJkaL7VfWBh9sMUXg4+fXqemq/4dmaCV1dqjTPxj+Sa2ldy+Gl+iXeQlI=
      app: itea-ci
      on:
        branch: master
        tags: true
    after_deploy: curl https://itea-ci.herokuapp.com
env:
  global:
  - MOZ_HEADLESS=1
