language: node_js
node_js: '10'

addons:
  firefox: latest

before_install: npm install -g @angular/cli
install: npm install

branches:
  only:
  - /.*/

stages:
  - name: buid
    if: branch != master
  - name: deploy
    if: (tag =~ ^v) AND (branch = master)
  - name: post_test
    if: (tag =~ ^v) AND (branch = master)

jobs:
  include:
  - stage: deploy
    deploy:
      provider: heroku
      api_key:
        secure: "b7ce0507-600b-4da2-b6b1-5f51ecb0d5a2"
      app: itea-ci
      on:
        branch: master
        tags: true
  - stage: post_test
    script: 'curl https://itea-ci.herokuapp.com'

env:
  global:
  - MOZ_HEADLESS=1
