language: node_js
node_js: '10'
addons:
  firefox: latest
before_install: npm install -g @angular/cli
install: npm install
branches:
  only:
  - "/.*/"
jobs:
  include:
  - stage: build
    deploy:
      provider: heroku
      api_key:
        secure: IC05EP/ciXawagJqMcIkoppZggytlgQNv3ZaRj2CtEuWeSPoZrKq+GC0M/9rOIElHba0Hj83A9j7ChBt39rvKtwy/1RZTjRhsQZ4u+jvtuoXQnY2Db9b6rlpWy52C/8GGKwddHBR4fPaAkpbUzU06+W4mc6VLkRa49tK4Q+GQTNKN9GckgdCgFqcPOlKtsX53xt1ht1uA9VcQhd5WS1rDl/M67UN4yye550y0R7Qvo7cE5Roe6ixe9PQckdtWzBv/2PBQpTMC6j0j7OXWBaiPaHeYe6FY3GE6Y448oHNkGB69kNNssldpfY3eVnLXmU8h0REZo8pChCYfdN2zYWk4jv0GtNAjSXQ+lbdb6t/gy57lIGNRewrLPODvbuGBwXb1j1SEqajoPUZhy7+9MPOAewUCETmNnS4rJ2HCNAORuNoAHoDR1Fv60/UEQUszbBslN6DQZinJHNz9sEqIKm74QUBrw/opOlOp2MHVsDZWYbDvMNSyW+NKuTHpL14CZ3WvxRdumNXNuLBOJG/WqAJxsFK7sDv/cPSaWhX1IrSIcpQi4h3ohryAxspAMXYVff3NJ2zk2CKqW+OhWxhrA1vI6i0AtbirCEgjJveVsEsLj4blDYK0DvXUu7dC5yfKvDI//o9sH65q8e+kufc4GqCg3z7RtM0N7whCvks7qcOqY4=
      app: itea-ci
      on:
        branch: master
        tags: true
    after_deploy: curl https://itea-ci.herokuapp.com
env:
  global:
  - MOZ_HEADLESS=1
